version: '3.8'
services:
  mysqldb:
    container_name: employee_db
    image: mysql:5.7
    restart: always
    ports:
      - 3333:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=employee_db
    volumes:
      - db:/var/lib/mysql
volumes:
  db: